name: AI PR Review

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  ai-review:
    if: startsWith(github.event.comment.body, '/review-with') || startsWith(github.event.review.body, '/review-with')
    uses: pipedrive/gha-setup/.github/workflows/reusable_ai-pr-review.yaml@master
    with:
      trigger_phrase: ${{ github.event.comment.body || github.event.review.body }}
    secrets: inherit
